function refresh-shell-cache --description "Regenerate cached shell init files in conf.d"
    set -l cache_dir $__fish_config_dir/conf.d

    echo "Regenerating shell init caches in $cache_dir..."

    if type -q starship
        starship init fish >$cache_dir/cache-starship.fish
        echo "  [ok] starship"
    else
        echo "  [skip] starship (not installed)"
    end

    if type -q zoxide
        zoxide init fish >$cache_dir/cache-zoxide.fish
        echo "  [ok] zoxide"
    else
        echo "  [skip] zoxide (not installed)"
    end

    if type -q atuin
        begin
            echo '# Auto-generated by refresh-shell-cache. Do not edit.'
            echo 'status is-interactive; or return'
            atuin init fish
        end >$cache_dir/cache-atuin.fish
        echo "  [ok] atuin"
    else
        echo "  [skip] atuin (not installed)"
    end

    if type -q zmx
        begin
            echo '# Auto-generated by refresh-shell-cache. Do not edit.'
            echo 'type -q zmx; or return'
            zmx completions fish
        end >$cache_dir/cache-zmx.fish
        echo "  [ok] zmx"
    else
        echo "  [skip] zmx (not installed)"
    end

    echo "Done. Open a new shell to pick up the changes."
end
