#set -x DOTNET_ROOT $HOME/.dotnet
#fish_add_path $DOTNET_ROOT
# Homebrew .NET on Apple Silicon

# Light = themes/dayfox.fish, dark = themes/carbonfox.fish (matches wezterm + nvim)
function setscheme
    if test -z "$argv"
        echo "Usage: setscheme <themename>"
        return 1
    end

    set -l config_home "$XDG_CONFIG_HOME"
    if test -z "$config_home"
        set config_home "$HOME/.config"
    end

    set -l theme_path "$config_home/fish/themes/$argv[1].fish"

    if test -f "$theme_path"
        source "$theme_path"
        set -gx THEME $argv[1]
    else
        echo "Theme '$argv[1]' not found. Looked for: $theme_path"
        return 1
    end
end

# setscheme tokyonight_moon
# Mirror wezterm's appearance.is_dark() on macOS; Linux defaults to dark
if test (uname) = Darwin
    if test "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" = Dark
        setscheme carbonfox
    else
        setscheme dayfox
    end
else
    setscheme carbonfox
end

set -gx TERM xterm-256color

if test (uname) = Darwin
    set -x DOTNET_ROOT /opt/homebrew/opt/dotnet/libexec
else if command -q dotnet
    # Nix: dotnet is a symlink into the store. Resolve it so framework-dependent
    # apphosts (dotnet tools like easy-dotnet's server) can find the runtime.
    set -x DOTNET_ROOT (path dirname (realpath (command -v dotnet)))
else
    set -x DOTNET_ROOT $HOME/.dotnet
end
set -gx EDITOR nvim

set -g fish_key_bindings fish_vi_key_bindings
bind ctrl-e edit_command_buffer

set -gx SQLCMDMAXVARTYPEWIDTH 36
set -gx SQLCMDMAXFIXEDTYPEWIDTH 36

if test (uname) = Darwin
    fish_add_path /opt/homebrew/opt/container/bin
    fish_add_path /opt/homebrew/bin
    fish_add_path /opt/homebrew/sbin
    fish_add_path /opt/vagrant/bin
end
fish_add_path $HOME/.bun/bin
fish_add_path $HOME/bin
fish_add_path $DOTNET_ROOT
fish_add_path $DOTNET_ROOT/tools
fish_add_path $HOME/.dotnet/tools
if test (uname) = Darwin
    fish_add_path /Applications/Docker.app/Contents/Resources/bin
    fish_add_path $HOME/Library/Application\ Support/JetBrains/Toolbox/scripts
end
fish_add_path $HOME/.opencode/bin
fish_add_path $HOME/.config/fish/scripts
fish_add_path /Applications/Obsidian.app/Contents/MacOS

set -gx DOTNET_WATCH_RESTART_ON_RUDE_EDIT 1
set -gx DOTNET_CLI_TELEMETRY_OPTOUT 1

test -f ~/.config/fish/secrets.fish && source ~/.config/fish/secrets.fish

alias ql "qlmanage -p $argv >/dev/null 2>&1"
alias vim nvim
function f
    set -l dir (fd --type directory | fzf)
    and cd $dir
end

# starship, zoxide, atuin, and zmx completions are loaded from cached
# conf.d/cache-*.fish files generated by `refresh-shell-cache`. Re-run that
# function after upgrading those tools.

# set -gx VOLTA_HOME "$HOME/.volta"
# set -gx PATH "$VOLTA_HOME/bin" $PATH

set -gx SEARXNG_API_URL "http://10.0.0.198:9010/search"

# Unset the default fish greeting text which messes up Zellij
set fish_greeting

# Check if we're in an interactive shell
if status is-interactive
    # # At this point, specify the Zellij config dir, so we can launch it manually if we want to
    # export ZELLIJ_CONFIG_DIR=$HOME/.config/zellij
    # export ZELLIJ_AUTO_ATTACH=true
    #
    # # Check if our Terminal emulator is Ghostty
    if [ "$TERM" = xterm-ghostty ]
        source "$GHOSTTY_RESOURCES_DIR"/shell-integration/fish/vendor_conf.d/ghostty-shell-integration.fish
        #     # Launch zellij
        #     #eval (zellij setup --generate-auto-start fish | string collect)
        #     if not set -q ZELLIJ
        #         if test "$ZELLIJ_AUTO_ATTACH" = "true"
        #             zellij attach default -c
        #         else
        #             zellij
        #         end
        #
        #         if test "$ZELLIJ_AUTO_EXIT" = "true"
        #             kill $fish_pid
        #         end
        #     end
    end
end

if status is-interactive
    mise activate fish | source
else
    mise activate fish --shims | source
end

# pnpm
set -gx PNPM_HOME $HOME/Library/pnpm
if not string match -q -- $PNPM_HOME $PATH
    set -gx PATH "$PNPM_HOME" $PATH
end
# pnpm end

# export DOCKER_HOST=unix://${HOME}/.colima/default/docker.sock
# export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
# export TESTCONTAINERS_HOST_OVERRIDE=$(colima ls -j | jq -r '.address')
# set -gx DOCKER_HOST unix://$HOME/.colima/default/docker.sock
# set -gx TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE /var/run/docker.sock
# set -gx TESTCONTAINERS_HOST_OVERRIDE (colima ls -j | jq -r '.address')

function safe
    safehouse --add-dirs-ro="$HOME/projects" $argv
end

# Sandboxed helpers without overriding the original binary names.
function sandbox-claude
    safe claude --dangerously-skip-permissions $argv
end

function sandbox-codex
    safe codex --dangerously-bypass-approvals-and-sandbox $argv
end

function sandbox-amp
    safe amp --dangerously-allow-all $argv
end

function sandbox-gemini
    set -lx NO_BROWSER true
    safe gemini --yolo $argv
end

# Custom sandbox-exec profile shortcuts (uses ~/.config/sandbox-exec/agent.sb)
function sandbox-custom-claude
    ~/.config/sandbox-exec/run-sandboxed.sh claude --dangerously-skip-permissions $argv
end

function sandbox-custom-gemini
    set -lx NO_BROWSER true
    ~/.config/sandbox-exec/run-sandboxed.sh gemini --yolo $argv
end

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init2.fish 2>/dev/null || :

# --- Shared aliases (from nix base) ---
if test (uname) = Darwin
    alias copy pbcopy
    alias paste pbpaste
else
    alias copy 'xclip -selection clipboard'
    alias paste 'xclip -o -selection clipboard'
end
alias cat bat
alias gogit 'cd ~/git'
function '!!' --description 'Run last command from history'
    eval $history[1]
end

# --- Tool integrations ---
if type -q fzf
    fzf --fish | source
end

# FZF keybindings (ctrl-e=vim, ctrl-a=project, ctrl-t=file, ctrl-r=history)
for mode in insert default normal
    bind -M $mode \ce fzf-vim-widget
    bind -M $mode \a fzf-project-widget
    bind -M $mode \ct fzf-file-widget-wrapped
    bind -M $mode \cR fzf-history-widget-wrapped
end

# jk to exit insert mode
bind -M insert jk "if commandline -P; commandline -f cancel; else; set fish_bind_mode default; commandline -f backward-char force-repaint; end"

# OP plugin alias
# set -gx OP_PLUGIN_ALIASES_SOURCED 1
# alias gh "op plugin run -- gh"

if type -q zoxide
    zoxide init fish | source
end

if type -q direnv
    direnv hook fish | source
end

if type -q atuin
    atuin init fish | source
end

if test "$TERM" != dumb
    if type -q starship
        starship init fish | source
    end
end
